In [1]:
import numpy as np

In [4]:
list_ = [1, 2, 3, 4, 5]
print(list_)
print(type(list_))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
arr = np.array(list_)
print(arr)
print(type(arr))

#initializing np array of certain size with either 0 (np.empty/zeroes) or 1 (np.ones)
arr1 = np.empty([5, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[6.23042070e-307 1.89146896e-307 1.37961302e-306 6.23053614e-307
  6.23053954e-307]
 [9.34609790e-307 8.45593934e-307 9.34600963e-307 1.86921143e-306
  6.23061763e-307]
 [8.90104239e-307 6.89804132e-307 1.33512376e-306 6.89806849e-307
  9.34609790e-307]
 [1.69121096e-306 1.05700515e-307 1.11261774e-306 1.29060871e-306
  8.34424766e-308]
 [8.34445138e-308 7.56577398e-307 9.34600284e-307 2.22507386e-306
  2.46151512e-312]]
<class 'numpy.ndarray'>


In [10]:
list_2d = [[1, 2, 3], [1, 2, 3]]
print(list_2d)
print(type(list_2d))

[[1, 2, 3], [1, 2, 3]]
<class 'list'>


In [11]:
arr_2d = np.array(list_2d)
print(arr_2d)
print(type(arr_2d))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [14]:
#arange(start, stop, step) return an array of evenly spaced values within a given interval
np.arange(0, 15)

np.arange(15, -5, -1)

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, -1,
       -2, -3, -4])

In [19]:
#using reshape(rows, columns) to reshape existing np array to 2d
np.arange(0, 15).reshape(3, 5)

test_arr = np.zeros(6)
test_arr.reshape(2, 3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#change default value of array value 
np.ones(15, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
#create identity matrix of a number n np.eye(n)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
#random number rand (which will fill the ndarray with random samples from a uniform distribution over [0, 1))
np.random.rand(5)

array([0.32563842, 0.46550052, 0.78797722, 0.27716027, 0.05618366])

In [23]:
#randn (which will return a sample (or samples) from the standard normal distribution.)
np.random.rand(5)

array([0.37591677, 0.26289923, 0.32315823, 0.0066168 , 0.65070598])

In [24]:
# randint(low, high, size) to generate a single or multiple random integers between [low, high).
#The size parameter specifies how many we'd like. Let's see a few examples.
np.random.randint(1, 100)

79

In [25]:
np.random.randint(1, 100, 15)

array([80, 73,  9, 13, 15, 82, 67,  7, 36, 71, 45, 53, 16, 87, 61])

In [27]:
#min, max, argmin, and
#argmax. The only difference between the two arg methods is that they'll instead return the index
#position of the min/max value. 

A = np.random.randint(0, 100, 20).reshape(4, 5)
print(f"Smalles value of A {A.min()}, and is located at {A.argmin()} ")

Smalles value of A 5, and is located at 6 


In [29]:
#Get array shape
A.shape

(4, 5)

In [32]:
#matrix multiplication is matmul
C = np.arange(0, 15).reshape(3, 5)
D = np.arange(0, 15).reshape(5, 3)
print(C)
print(D)
np.matmul(C, D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

In [33]:
#loop through
#every element in your ndarray and return a new ndarray that replaces the element with x if the
#condition is met, and y if the condition is not met.
# where(condition, x, y)
np.where(C%2 == 0, 2, C*100) #C here is represented as the array but inside the brackets they are also each variable

array([[   2,  100,    2,  300,    2],
       [ 500,    2,  700,    2,  900],
       [   2, 1100,    2, 1300,    2]])

In [37]:
B = np.arange(50).reshape(5, 10)
print(B)
#Only now we have to specify both the row sections of interest and column sections of interest. 
#Say I want rows 0-2 from B but only the elements in that row corresponding to columns 3-5

B[0:2, 3:5]


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([[ 3,  4],
       [13, 14]])

In [38]:
C = np.arange(50).reshape(10, 5)
print(C)

#Index arrays using comparision operators
C%2 == 0

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [39]:
#Sum of total true answers
(C%2==0).sum()

25

In [42]:
#passing the boolean array as an index (Filter out all the false value inside of an array. Leaving us with a new arra
#of true values)
D = C[C%2==0]

print(D)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
